# Generated by Django 4.0.6 on 2022-07-20 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supers', '0001_initial'),
        ('hv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hv',
            name='super_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='supers.supers'),
        ),
    ]
