# Generated by Django 4.0.6 on 2022-07-20 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supers', '0001_initial'),
        ('hv', '0002_hv_super_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hv',
            name='super_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='supers.supers'),
            preserve_default=False,
        ),
    ]
